<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="apps.certifier.tests.internal.test_models" tests="4" time="0.00451231002808"><testcase classname="apps.certifier.tests.internal.test_models.CertifierCertificationResponseBaseTests" name="test_is_exception" time="0.000358104705811"></testcase><testcase classname="apps.certifier.tests.internal.test_models.CertifierCertificationResponseBaseTests" name="test_is_alert" time="0.000415086746216"></testcase><testcase classname="apps.certifier.tests.internal.test_models.CertifierCertificationBaseTests" name="test_get_process_key_from_cert_key" time="0.00168204307556"></testcase><testcase classname="apps.certifier.tests.internal.test_models.CertifierCertificationBaseTests" name="test_get_process_key" time="0.00205707550049"></testcase></testsuite>
